name: "arr"

x-lockdown: &lockdown
  # prevents write access to the image itself
  read_only: true
  # prevents any process within the container to gain more privileges
  security_opt:
    - "no-new-privileges=true"

services:
  configarr:
    image: "keksiqc/configarr:1.20.0"
    <<: *lockdown
    environment:
      TZ: "Europe/Zurich"
      # sync configarr every two hours
      CONFIGARR_SCHEDULE: "0 */2 * * *"
    networks:
      frontend:
    volumes:
      - "configarr.etc:/configarr/etc"
      - "configarr.var:/configarr/var"
    restart: "always"

volumes:
  configarr.etc:
  configarr.var:

networks:
  frontend:
